Fix compiling issues in Map.h with newer g++ versions
My project that uses MiniSat did not compile anymore after
updating from Ubuntu 15.10 to 16.10
The following error message was shown:
/home/patrick/uni/SEA/libs/minisat/mtl/Map.h:32:99: error: missing template arguments before ‘(’ token
 late<class K> struct Hash  { uint32_t operator()(const K& k)               const { return hash(k);  } };
                                                                                               ^
/home/patrick/uni/SEA/libs/minisat/mtl/Map.h: In member function ‘uint32_t Minisat::DeepHash<K>::operator()(const K*) const’:
/home/patrick/uni/SEA/libs/minisat/mtl/Map.h:35:103: error: missing template arguments before ‘(’ token
 class K> struct DeepHash  { uint32_t operator()(const K* k)               const { return hash(*k);  } };